### Site Settings ###
title               : PhenoApps
description         : >-
                      Apps for phenotyping
baseurl             : ""                     			# Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : PhenoApps/phenoapps.org     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)
mailchimp-list      : //wheatgenetics.us14.list-manage.com/subscribe/post?u=e6dcddecd0b4a60f7bb39cba7&amp;id=0f0172c6b8&amp

### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/privacy.md
  - pages/terms.md
  - pages/mailchimp.md


### Author Info ###
author:
  name              : Trevor Rife
  email             : twrife@clemson.edu
  github            : PhenoApps
  twitter           : PhenoApps
# image             : https://i.imgur.com/uyDNQnn.jpg
# behance           : your_username
# dribbble          : your_username
# facebook          : your_username
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
# linkedin          : your_username
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Collections ###
collections:
  projects:
    output: true
    permalink: /apps/:name
  hardwares:
    output: true
    permalink: /hardware2/:name


### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: G-VXKQM0GBPQ


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "hardwares"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
